//
//  LegalTermsManager.swift
//  Bullseye
//

import Foundation

enum LegalTermsManager {
    static let currentVersion = "2025-06-27-v1"
    private static let acceptedVersionKey = "bullseye.terms.accepted.version"

    static var hasAcceptedCurrentTerms: Bool {
        UserDefaults.standard.string(forKey: acceptedVersionKey) == currentVersion
    }

    static func acceptCurrentTerms() {
        UserDefaults.standard.set(currentVersion, forKey: acceptedVersionKey)
    }

    static let termsTitle = "Terms of Use & Risk Disclosure"

    static let termsBody = """
    IMPORTANT — PLEASE READ CAREFULLY

    By tapping "I Accept", you agree to these Terms of Use and Risk Disclosure ("Terms") for Bullseye AI ("Bullseye", "we", "us", "the App"). If you do not agree, do not use the App.

    1. NOT INVESTMENT ADVICE
    Bullseye provides informational and educational tools only. Nothing in the App constitutes investment, financial, legal, or tax advice. We are not a registered investment adviser, broker-dealer, or fiduciary. All predictions, scores, alerts, congress/insider feeds, event-market suggestions, and AI outputs are opinions generated by algorithms and third-party data — not recommendations to buy or sell any security or contract.

    2. NO GUARANTEE OF ACCURACY
    Market prices, including crypto, may differ from prices shown on Robinhood, Webull, Coinbase, or other platforms due to exchange, spread, latency, and data provider methodology. We use third-party sources (e.g., Yahoo Finance, CoinGecko). Prices can be delayed, incomplete, or incorrect. Past prediction accuracy does not guarantee future results.

    3. SUBSTANTIAL RISK OF LOSS
    Trading stocks, options, futures, forex, crypto, and event contracts involves substantial risk of loss and is not suitable for every investor. You may lose some or all of your invested capital. Only trade with money you can afford to lose.

    4. PAPER TRADING VS LIVE TRADING
    Paper (fake money) results do not reflect real-world slippage, fees, liquidity, or emotional factors. Opening a broker app from Bullseye does not execute trades through us. You are solely responsible for orders placed with third-party brokers.

    5. AI LIMITATIONS
    AI and technical models can be wrong, biased, or outdated. Confidence scores are estimates, not probabilities of profit. You must independently verify all information before making financial decisions.

    6. REGULATORY & ELIGIBILITY
    You represent that you are at least 18 years old (or the age of majority in your jurisdiction) and legally permitted to use financial information services in your location. Event-market features may not be available in all jurisdictions.

    7. DATA & PRIVACY
    We identify your device for token balance, subscriptions, and watchlists without requiring login. Do not share your device with others if you wish to keep usage private.

    8. LIMITATION OF LIABILITY
    TO THE MAXIMUM EXTENT PERMITTED BY LAW, BULLSEYE AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE APP. OUR TOTAL LIABILITY SHALL NOT EXCEED THE GREATER OF (A) AMOUNTS YOU PAID US IN THE PRIOR 12 MONTHS OR (B) USD $100.

    9. INDEMNIFICATION
    You agree to indemnify and hold harmless Bullseye from claims arising out of your trading decisions, misuse of the App, or violation of these Terms.

    10. ARBITRATION & CLASS ACTION WAIVER (U.S.)
    Any dispute arising from these Terms or the App shall be resolved by binding individual arbitration under AAA rules, not in court, except you may bring qualifying claims in small claims court. YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION.

    11. CHANGES
    We may update these Terms. Continued use after notice constitutes acceptance. Material changes may require re-acceptance in the App.

    12. CONTACT
    Questions: support@bullseye-ai.app (placeholder — update with your legal contact before App Store submission).

    By accepting, you acknowledge that you have read, understood, and agree to these Terms and that you are solely responsible for your investment decisions.
    """
}
